chore: instal corepack if no corepack installed

diff --git a/.github/workflows/deploy-to-ec2.yml b/.github/workflows/deploy-to-ec2.yml
--- a/.github/workflows/deploy-to-ec2.yml
+++ b/.github/workflows/deploy-to-ec2.yml
@@ -34,8 +34,13 @@ jobs:
               source ~/.profile
               cd ~/app/server
              
-              corepack enable pnpm
-
+              
+              if ! command -v pnpm &> /dev/null; then
+                echo "corepack not found! Installing..."
+                npm install --global corepack@latest
+                corepack enable pnpm
+              fi
+              
               if ! command -v pnpm &> /dev/null; then
                 echo "pnpm not found! Installing..."
                 corepack prepare pnpm@latest --activate
